---
threshold: 14

smtp:
  from: cert-monitor@toolbox.talapas.uoregon.edu
  to:
    - lcrown@uoregon.edu
  server: smtp.uoregon.edu
  port: 25

domains:
  - is-hpc-metrics.uoregon.edu
  - is-hpc-graf.uoregon.edu
  - talapas-ln1.uoregon.edu
